/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as FolderSlugFeedRouteImport } from './routes/$folderSlug.feed'
import { Route as FolderSlugXmlRouteImport } from './routes/$folderSlug.xml'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedFolderSlugRouteImport } from './routes/_protected/$folderSlug'
import { Route as ProtectedAllRouteImport } from './routes/_protected/all'
import { Route as ProtectedDiscoverRouteImport } from './routes/_protected/discover'
import { Route as ProtectedFavoritesRouteImport } from './routes/_protected/favorites'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedSourcesRouteImport } from './routes/_protected/sources'
import { Route as ProtectedTodayRouteImport } from './routes/_protected/today'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiWorkspaceDataRouteImport } from './routes/api/workspace-data'
import { Route as SprkFolderSlugRouteImport } from './routes/sprk.$folderSlug'
import { Route as FolderSlugFeedSlugFeedRouteImport } from './routes/$folderSlug.$feedSlug.feed'
import { Route as FolderSlugFeedSlugXmlRouteImport } from './routes/$folderSlug.$feedSlug.xml'
import { Route as ProtectedFolderSlugIndexRouteImport } from './routes/_protected/$folderSlug/index'
import { Route as ProtectedDashboardAiRouteImport } from './routes/_protected/dashboard.ai'
import { Route as ProtectedDeveloperKeysRouteImport } from './routes/_protected/developer.keys'
import { Route as ProtectedDeveloperMcpRouteImport } from './routes/_protected/developer.mcp'
import { Route as ProtectedDiscoverIndexRouteImport } from './routes/_protected/discover/index'
import { Route as ProtectedDiscoverCategorySlugRouteImport } from './routes/_protected/discover/$categorySlug'
import { Route as ProtectedFeedFeedSlugRouteImport } from './routes/_protected/feed.$feedSlug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiDodoWebhooksRouteImport } from './routes/api/dodo.webhooks'
import { Route as ApiFeedsShareRouteImport } from './routes/api/feeds.share'
import { Route as ApiFoldersAddToWorkspaceRouteImport } from './routes/api/folders.add-to-workspace'
import { Route as ApiFoldersShareRouteImport } from './routes/api/folders.share'
import { Route as ApiRssSlugRouteImport } from './routes/api/rss.$slug'
import { Route as ApiSharedFolderIdRouteImport } from './routes/api/shared.$folderId'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1.$'
import { Route as ProtectedFolderSlugFeedSlugIndexRouteImport } from './routes/_protected/$folderSlug/$feedSlug/index'
import { Route as ProtectedDashboardAiIndexRouteImport } from './routes/_protected/dashboard.ai/index'
import { Route as ProtectedDashboardAiThreadIdRouteImport } from './routes/_protected/dashboard.ai/$threadId'
import { Route as ProtectedSettingsWorkspacesSlugRouteImport } from './routes/_protected/settings_.workspaces.$slug'
import { Route as ProtectedWorkspacesSlugSettingsRouteImport } from './routes/_protected/workspaces.$slug.settings'
import { Route as ApiInternalPlatformSplatRouteImport } from './routes/api/internal.platform.$'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderSlugFeedRoute = FolderSlugFeedRouteImport.update({
  id: '/$folderSlug/feed',
  path: '/$folderSlug/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderSlugXmlRoute = FolderSlugXmlRouteImport.update({
  id: '/$folderSlug/xml',
  path: '/$folderSlug/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFolderSlugRoute = ProtectedFolderSlugRouteImport.update({
  id: '/$folderSlug',
  path: '/$folderSlug',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAllRoute = ProtectedAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDiscoverRoute = ProtectedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFavoritesRoute = ProtectedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSourcesRoute = ProtectedSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTodayRoute = ProtectedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceDataRoute = ApiWorkspaceDataRouteImport.update({
  id: '/api/workspace-data',
  path: '/api/workspace-data',
  getParentRoute: () => rootRouteImport,
} as any)
const SprkFolderSlugRoute = SprkFolderSlugRouteImport.update({
  id: '/sprk/$folderSlug',
  path: '/sprk/$folderSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderSlugFeedSlugFeedRoute = FolderSlugFeedSlugFeedRouteImport.update({
  id: '/$folderSlug/$feedSlug/feed',
  path: '/$folderSlug/$feedSlug/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderSlugFeedSlugXmlRoute = FolderSlugFeedSlugXmlRouteImport.update({
  id: '/$folderSlug/$feedSlug/xml',
  path: '/$folderSlug/$feedSlug/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedFolderSlugIndexRoute =
  ProtectedFolderSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedFolderSlugRoute,
  } as any)
const ProtectedDashboardAiRoute = ProtectedDashboardAiRouteImport.update({
  id: '/dashboard/ai',
  path: '/dashboard/ai',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDeveloperKeysRoute = ProtectedDeveloperKeysRouteImport.update({
  id: '/developer/keys',
  path: '/developer/keys',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDeveloperMcpRoute = ProtectedDeveloperMcpRouteImport.update({
  id: '/developer/mcp',
  path: '/developer/mcp',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDiscoverIndexRoute = ProtectedDiscoverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDiscoverRoute,
} as any)
const ProtectedDiscoverCategorySlugRoute =
  ProtectedDiscoverCategorySlugRouteImport.update({
    id: '/$categorySlug',
    path: '/$categorySlug',
    getParentRoute: () => ProtectedDiscoverRoute,
  } as any)
const ProtectedFeedFeedSlugRoute = ProtectedFeedFeedSlugRouteImport.update({
  id: '/feed/$feedSlug',
  path: '/feed/$feedSlug',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDodoWebhooksRoute = ApiDodoWebhooksRouteImport.update({
  id: '/api/dodo/webhooks',
  path: '/api/dodo/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedsShareRoute = ApiFeedsShareRouteImport.update({
  id: '/api/feeds/share',
  path: '/api/feeds/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFoldersAddToWorkspaceRoute =
  ApiFoldersAddToWorkspaceRouteImport.update({
    id: '/api/folders/add-to-workspace',
    path: '/api/folders/add-to-workspace',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFoldersShareRoute = ApiFoldersShareRouteImport.update({
  id: '/api/folders/share',
  path: '/api/folders/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRssSlugRoute = ApiRssSlugRouteImport.update({
  id: '/api/rss/$slug',
  path: '/api/rss/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharedFolderIdRoute = ApiSharedFolderIdRouteImport.update({
  id: '/api/shared/$folderId',
  path: '/api/shared/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedFolderSlugFeedSlugIndexRoute =
  ProtectedFolderSlugFeedSlugIndexRouteImport.update({
    id: '/$feedSlug/',
    path: '/$feedSlug/',
    getParentRoute: () => ProtectedFolderSlugRoute,
  } as any)
const ProtectedDashboardAiIndexRoute =
  ProtectedDashboardAiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardAiRoute,
  } as any)
const ProtectedDashboardAiThreadIdRoute =
  ProtectedDashboardAiThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => ProtectedDashboardAiRoute,
  } as any)
const ProtectedSettingsWorkspacesSlugRoute =
  ProtectedSettingsWorkspacesSlugRouteImport.update({
    id: '/settings_/workspaces/$slug',
    path: '/settings/workspaces/$slug',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedWorkspacesSlugSettingsRoute =
  ProtectedWorkspacesSlugSettingsRouteImport.update({
    id: '/workspaces/$slug/settings',
    path: '/workspaces/$slug/settings',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ApiInternalPlatformSplatRoute =
  ApiInternalPlatformSplatRouteImport.update({
    id: '/api/internal/platform/$',
    path: '/api/internal/platform/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/$folderSlug/feed': typeof FolderSlugFeedRoute
  '/$folderSlug/xml': typeof FolderSlugXmlRoute
  '/$folderSlug': typeof ProtectedFolderSlugRouteWithChildren
  '/all': typeof ProtectedAllRoute
  '/discover': typeof ProtectedDiscoverRouteWithChildren
  '/favorites': typeof ProtectedFavoritesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/sources': typeof ProtectedSourcesRoute
  '/today': typeof ProtectedTodayRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/workspace-data': typeof ApiWorkspaceDataRoute
  '/sprk/$folderSlug': typeof SprkFolderSlugRoute
  '/$folderSlug/$feedSlug/feed': typeof FolderSlugFeedSlugFeedRoute
  '/$folderSlug/$feedSlug/xml': typeof FolderSlugFeedSlugXmlRoute
  '/dashboard/ai': typeof ProtectedDashboardAiRouteWithChildren
  '/developer/keys': typeof ProtectedDeveloperKeysRoute
  '/developer/mcp': typeof ProtectedDeveloperMcpRoute
  '/discover/$categorySlug': typeof ProtectedDiscoverCategorySlugRoute
  '/feed/$feedSlug': typeof ProtectedFeedFeedSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dodo/webhooks': typeof ApiDodoWebhooksRoute
  '/api/feeds/share': typeof ApiFeedsShareRoute
  '/api/folders/add-to-workspace': typeof ApiFoldersAddToWorkspaceRoute
  '/api/folders/share': typeof ApiFoldersShareRoute
  '/api/rss/$slug': typeof ApiRssSlugRoute
  '/api/shared/$folderId': typeof ApiSharedFolderIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/$folderSlug/': typeof ProtectedFolderSlugIndexRoute
  '/discover/': typeof ProtectedDiscoverIndexRoute
  '/dashboard/ai/$threadId': typeof ProtectedDashboardAiThreadIdRoute
  '/settings/workspaces/$slug': typeof ProtectedSettingsWorkspacesSlugRoute
  '/workspaces/$slug/settings': typeof ProtectedWorkspacesSlugSettingsRoute
  '/api/internal/platform/$': typeof ApiInternalPlatformSplatRoute
  '/$folderSlug/$feedSlug/': typeof ProtectedFolderSlugFeedSlugIndexRoute
  '/dashboard/ai/': typeof ProtectedDashboardAiIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/$folderSlug/feed': typeof FolderSlugFeedRoute
  '/$folderSlug/xml': typeof FolderSlugXmlRoute
  '/all': typeof ProtectedAllRoute
  '/favorites': typeof ProtectedFavoritesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/sources': typeof ProtectedSourcesRoute
  '/today': typeof ProtectedTodayRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/workspace-data': typeof ApiWorkspaceDataRoute
  '/sprk/$folderSlug': typeof SprkFolderSlugRoute
  '/': typeof ProtectedIndexRoute
  '/$folderSlug/$feedSlug/feed': typeof FolderSlugFeedSlugFeedRoute
  '/$folderSlug/$feedSlug/xml': typeof FolderSlugFeedSlugXmlRoute
  '/developer/keys': typeof ProtectedDeveloperKeysRoute
  '/developer/mcp': typeof ProtectedDeveloperMcpRoute
  '/discover/$categorySlug': typeof ProtectedDiscoverCategorySlugRoute
  '/feed/$feedSlug': typeof ProtectedFeedFeedSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dodo/webhooks': typeof ApiDodoWebhooksRoute
  '/api/feeds/share': typeof ApiFeedsShareRoute
  '/api/folders/add-to-workspace': typeof ApiFoldersAddToWorkspaceRoute
  '/api/folders/share': typeof ApiFoldersShareRoute
  '/api/rss/$slug': typeof ApiRssSlugRoute
  '/api/shared/$folderId': typeof ApiSharedFolderIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/$folderSlug': typeof ProtectedFolderSlugIndexRoute
  '/discover': typeof ProtectedDiscoverIndexRoute
  '/dashboard/ai/$threadId': typeof ProtectedDashboardAiThreadIdRoute
  '/settings/workspaces/$slug': typeof ProtectedSettingsWorkspacesSlugRoute
  '/workspaces/$slug/settings': typeof ProtectedWorkspacesSlugSettingsRoute
  '/api/internal/platform/$': typeof ApiInternalPlatformSplatRoute
  '/$folderSlug/$feedSlug': typeof ProtectedFolderSlugFeedSlugIndexRoute
  '/dashboard/ai': typeof ProtectedDashboardAiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/$folderSlug/feed': typeof FolderSlugFeedRoute
  '/$folderSlug/xml': typeof FolderSlugXmlRoute
  '/_protected/$folderSlug': typeof ProtectedFolderSlugRouteWithChildren
  '/_protected/all': typeof ProtectedAllRoute
  '/_protected/discover': typeof ProtectedDiscoverRouteWithChildren
  '/_protected/favorites': typeof ProtectedFavoritesRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/sources': typeof ProtectedSourcesRoute
  '/_protected/today': typeof ProtectedTodayRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/workspace-data': typeof ApiWorkspaceDataRoute
  '/sprk/$folderSlug': typeof SprkFolderSlugRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/$folderSlug/$feedSlug/feed': typeof FolderSlugFeedSlugFeedRoute
  '/$folderSlug/$feedSlug/xml': typeof FolderSlugFeedSlugXmlRoute
  '/_protected/dashboard/ai': typeof ProtectedDashboardAiRouteWithChildren
  '/_protected/developer/keys': typeof ProtectedDeveloperKeysRoute
  '/_protected/developer/mcp': typeof ProtectedDeveloperMcpRoute
  '/_protected/discover/$categorySlug': typeof ProtectedDiscoverCategorySlugRoute
  '/_protected/feed/$feedSlug': typeof ProtectedFeedFeedSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dodo/webhooks': typeof ApiDodoWebhooksRoute
  '/api/feeds/share': typeof ApiFeedsShareRoute
  '/api/folders/add-to-workspace': typeof ApiFoldersAddToWorkspaceRoute
  '/api/folders/share': typeof ApiFoldersShareRoute
  '/api/rss/$slug': typeof ApiRssSlugRoute
  '/api/shared/$folderId': typeof ApiSharedFolderIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_protected/$folderSlug/': typeof ProtectedFolderSlugIndexRoute
  '/_protected/discover/': typeof ProtectedDiscoverIndexRoute
  '/_protected/dashboard/ai/$threadId': typeof ProtectedDashboardAiThreadIdRoute
  '/_protected/settings_/workspaces/$slug': typeof ProtectedSettingsWorkspacesSlugRoute
  '/_protected/workspaces/$slug/settings': typeof ProtectedWorkspacesSlugSettingsRoute
  '/api/internal/platform/$': typeof ApiInternalPlatformSplatRoute
  '/_protected/$folderSlug/$feedSlug/': typeof ProtectedFolderSlugFeedSlugIndexRoute
  '/_protected/dashboard/ai/': typeof ProtectedDashboardAiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/$folderSlug/feed'
    | '/$folderSlug/xml'
    | '/$folderSlug'
    | '/all'
    | '/discover'
    | '/favorites'
    | '/settings'
    | '/sources'
    | '/today'
    | '/api/chat'
    | '/api/health'
    | '/api/mcp'
    | '/api/workspace-data'
    | '/sprk/$folderSlug'
    | '/$folderSlug/$feedSlug/feed'
    | '/$folderSlug/$feedSlug/xml'
    | '/dashboard/ai'
    | '/developer/keys'
    | '/developer/mcp'
    | '/discover/$categorySlug'
    | '/feed/$feedSlug'
    | '/api/auth/$'
    | '/api/dodo/webhooks'
    | '/api/feeds/share'
    | '/api/folders/add-to-workspace'
    | '/api/folders/share'
    | '/api/rss/$slug'
    | '/api/shared/$folderId'
    | '/api/v1/$'
    | '/$folderSlug/'
    | '/discover/'
    | '/dashboard/ai/$threadId'
    | '/settings/workspaces/$slug'
    | '/workspaces/$slug/settings'
    | '/api/internal/platform/$'
    | '/$folderSlug/$feedSlug/'
    | '/dashboard/ai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/$folderSlug/feed'
    | '/$folderSlug/xml'
    | '/all'
    | '/favorites'
    | '/settings'
    | '/sources'
    | '/today'
    | '/api/chat'
    | '/api/health'
    | '/api/mcp'
    | '/api/workspace-data'
    | '/sprk/$folderSlug'
    | '/'
    | '/$folderSlug/$feedSlug/feed'
    | '/$folderSlug/$feedSlug/xml'
    | '/developer/keys'
    | '/developer/mcp'
    | '/discover/$categorySlug'
    | '/feed/$feedSlug'
    | '/api/auth/$'
    | '/api/dodo/webhooks'
    | '/api/feeds/share'
    | '/api/folders/add-to-workspace'
    | '/api/folders/share'
    | '/api/rss/$slug'
    | '/api/shared/$folderId'
    | '/api/v1/$'
    | '/$folderSlug'
    | '/discover'
    | '/dashboard/ai/$threadId'
    | '/settings/workspaces/$slug'
    | '/workspaces/$slug/settings'
    | '/api/internal/platform/$'
    | '/$folderSlug/$feedSlug'
    | '/dashboard/ai'
  id:
    | '__root__'
    | '/_protected'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/$folderSlug/feed'
    | '/$folderSlug/xml'
    | '/_protected/$folderSlug'
    | '/_protected/all'
    | '/_protected/discover'
    | '/_protected/favorites'
    | '/_protected/settings'
    | '/_protected/sources'
    | '/_protected/today'
    | '/api/chat'
    | '/api/health'
    | '/api/mcp'
    | '/api/workspace-data'
    | '/sprk/$folderSlug'
    | '/_protected/'
    | '/$folderSlug/$feedSlug/feed'
    | '/$folderSlug/$feedSlug/xml'
    | '/_protected/dashboard/ai'
    | '/_protected/developer/keys'
    | '/_protected/developer/mcp'
    | '/_protected/discover/$categorySlug'
    | '/_protected/feed/$feedSlug'
    | '/api/auth/$'
    | '/api/dodo/webhooks'
    | '/api/feeds/share'
    | '/api/folders/add-to-workspace'
    | '/api/folders/share'
    | '/api/rss/$slug'
    | '/api/shared/$folderId'
    | '/api/v1/$'
    | '/_protected/$folderSlug/'
    | '/_protected/discover/'
    | '/_protected/dashboard/ai/$threadId'
    | '/_protected/settings_/workspaces/$slug'
    | '/_protected/workspaces/$slug/settings'
    | '/api/internal/platform/$'
    | '/_protected/$folderSlug/$feedSlug/'
    | '/_protected/dashboard/ai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  FolderSlugFeedRoute: typeof FolderSlugFeedRoute
  FolderSlugXmlRoute: typeof FolderSlugXmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiWorkspaceDataRoute: typeof ApiWorkspaceDataRoute
  SprkFolderSlugRoute: typeof SprkFolderSlugRoute
  FolderSlugFeedSlugFeedRoute: typeof FolderSlugFeedSlugFeedRoute
  FolderSlugFeedSlugXmlRoute: typeof FolderSlugFeedSlugXmlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDodoWebhooksRoute: typeof ApiDodoWebhooksRoute
  ApiFeedsShareRoute: typeof ApiFeedsShareRoute
  ApiFoldersAddToWorkspaceRoute: typeof ApiFoldersAddToWorkspaceRoute
  ApiFoldersShareRoute: typeof ApiFoldersShareRoute
  ApiRssSlugRoute: typeof ApiRssSlugRoute
  ApiSharedFolderIdRoute: typeof ApiSharedFolderIdRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiInternalPlatformSplatRoute: typeof ApiInternalPlatformSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$folderSlug/feed': {
      id: '/$folderSlug/feed'
      path: '/$folderSlug/feed'
      fullPath: '/$folderSlug/feed'
      preLoaderRoute: typeof FolderSlugFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$folderSlug/xml': {
      id: '/$folderSlug/xml'
      path: '/$folderSlug/xml'
      fullPath: '/$folderSlug/xml'
      preLoaderRoute: typeof FolderSlugXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$folderSlug': {
      id: '/_protected/$folderSlug'
      path: '/$folderSlug'
      fullPath: '/$folderSlug'
      preLoaderRoute: typeof ProtectedFolderSlugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/all': {
      id: '/_protected/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof ProtectedAllRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/discover': {
      id: '/_protected/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof ProtectedDiscoverRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/favorites': {
      id: '/_protected/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof ProtectedFavoritesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/sources': {
      id: '/_protected/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof ProtectedSourcesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/today': {
      id: '/_protected/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof ProtectedTodayRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace-data': {
      id: '/api/workspace-data'
      path: '/api/workspace-data'
      fullPath: '/api/workspace-data'
      preLoaderRoute: typeof ApiWorkspaceDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprk/$folderSlug': {
      id: '/sprk/$folderSlug'
      path: '/sprk/$folderSlug'
      fullPath: '/sprk/$folderSlug'
      preLoaderRoute: typeof SprkFolderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$folderSlug/$feedSlug/feed': {
      id: '/$folderSlug/$feedSlug/feed'
      path: '/$folderSlug/$feedSlug/feed'
      fullPath: '/$folderSlug/$feedSlug/feed'
      preLoaderRoute: typeof FolderSlugFeedSlugFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$folderSlug/$feedSlug/xml': {
      id: '/$folderSlug/$feedSlug/xml'
      path: '/$folderSlug/$feedSlug/xml'
      fullPath: '/$folderSlug/$feedSlug/xml'
      preLoaderRoute: typeof FolderSlugFeedSlugXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/$folderSlug/': {
      id: '/_protected/$folderSlug/'
      path: '/'
      fullPath: '/$folderSlug/'
      preLoaderRoute: typeof ProtectedFolderSlugIndexRouteImport
      parentRoute: typeof ProtectedFolderSlugRoute
    }
    '/_protected/dashboard/ai': {
      id: '/_protected/dashboard/ai'
      path: '/dashboard/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof ProtectedDashboardAiRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/developer/keys': {
      id: '/_protected/developer/keys'
      path: '/developer/keys'
      fullPath: '/developer/keys'
      preLoaderRoute: typeof ProtectedDeveloperKeysRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/developer/mcp': {
      id: '/_protected/developer/mcp'
      path: '/developer/mcp'
      fullPath: '/developer/mcp'
      preLoaderRoute: typeof ProtectedDeveloperMcpRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/discover/': {
      id: '/_protected/discover/'
      path: '/'
      fullPath: '/discover/'
      preLoaderRoute: typeof ProtectedDiscoverIndexRouteImport
      parentRoute: typeof ProtectedDiscoverRoute
    }
    '/_protected/discover/$categorySlug': {
      id: '/_protected/discover/$categorySlug'
      path: '/$categorySlug'
      fullPath: '/discover/$categorySlug'
      preLoaderRoute: typeof ProtectedDiscoverCategorySlugRouteImport
      parentRoute: typeof ProtectedDiscoverRoute
    }
    '/_protected/feed/$feedSlug': {
      id: '/_protected/feed/$feedSlug'
      path: '/feed/$feedSlug'
      fullPath: '/feed/$feedSlug'
      preLoaderRoute: typeof ProtectedFeedFeedSlugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dodo/webhooks': {
      id: '/api/dodo/webhooks'
      path: '/api/dodo/webhooks'
      fullPath: '/api/dodo/webhooks'
      preLoaderRoute: typeof ApiDodoWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feeds/share': {
      id: '/api/feeds/share'
      path: '/api/feeds/share'
      fullPath: '/api/feeds/share'
      preLoaderRoute: typeof ApiFeedsShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/folders/add-to-workspace': {
      id: '/api/folders/add-to-workspace'
      path: '/api/folders/add-to-workspace'
      fullPath: '/api/folders/add-to-workspace'
      preLoaderRoute: typeof ApiFoldersAddToWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/folders/share': {
      id: '/api/folders/share'
      path: '/api/folders/share'
      fullPath: '/api/folders/share'
      preLoaderRoute: typeof ApiFoldersShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rss/$slug': {
      id: '/api/rss/$slug'
      path: '/api/rss/$slug'
      fullPath: '/api/rss/$slug'
      preLoaderRoute: typeof ApiRssSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shared/$folderId': {
      id: '/api/shared/$folderId'
      path: '/api/shared/$folderId'
      fullPath: '/api/shared/$folderId'
      preLoaderRoute: typeof ApiSharedFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/$folderSlug/$feedSlug/': {
      id: '/_protected/$folderSlug/$feedSlug/'
      path: '/$feedSlug'
      fullPath: '/$folderSlug/$feedSlug/'
      preLoaderRoute: typeof ProtectedFolderSlugFeedSlugIndexRouteImport
      parentRoute: typeof ProtectedFolderSlugRoute
    }
    '/_protected/dashboard/ai/': {
      id: '/_protected/dashboard/ai/'
      path: '/'
      fullPath: '/dashboard/ai/'
      preLoaderRoute: typeof ProtectedDashboardAiIndexRouteImport
      parentRoute: typeof ProtectedDashboardAiRoute
    }
    '/_protected/dashboard/ai/$threadId': {
      id: '/_protected/dashboard/ai/$threadId'
      path: '/$threadId'
      fullPath: '/dashboard/ai/$threadId'
      preLoaderRoute: typeof ProtectedDashboardAiThreadIdRouteImport
      parentRoute: typeof ProtectedDashboardAiRoute
    }
    '/_protected/settings_/workspaces/$slug': {
      id: '/_protected/settings_/workspaces/$slug'
      path: '/settings/workspaces/$slug'
      fullPath: '/settings/workspaces/$slug'
      preLoaderRoute: typeof ProtectedSettingsWorkspacesSlugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/workspaces/$slug/settings': {
      id: '/_protected/workspaces/$slug/settings'
      path: '/workspaces/$slug/settings'
      fullPath: '/workspaces/$slug/settings'
      preLoaderRoute: typeof ProtectedWorkspacesSlugSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/internal/platform/$': {
      id: '/api/internal/platform/$'
      path: '/api/internal/platform/$'
      fullPath: '/api/internal/platform/$'
      preLoaderRoute: typeof ApiInternalPlatformSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedFolderSlugRouteChildren {
  ProtectedFolderSlugIndexRoute: typeof ProtectedFolderSlugIndexRoute
  ProtectedFolderSlugFeedSlugIndexRoute: typeof ProtectedFolderSlugFeedSlugIndexRoute
}

const ProtectedFolderSlugRouteChildren: ProtectedFolderSlugRouteChildren = {
  ProtectedFolderSlugIndexRoute: ProtectedFolderSlugIndexRoute,
  ProtectedFolderSlugFeedSlugIndexRoute: ProtectedFolderSlugFeedSlugIndexRoute,
}

const ProtectedFolderSlugRouteWithChildren =
  ProtectedFolderSlugRoute._addFileChildren(ProtectedFolderSlugRouteChildren)

interface ProtectedDiscoverRouteChildren {
  ProtectedDiscoverCategorySlugRoute: typeof ProtectedDiscoverCategorySlugRoute
  ProtectedDiscoverIndexRoute: typeof ProtectedDiscoverIndexRoute
}

const ProtectedDiscoverRouteChildren: ProtectedDiscoverRouteChildren = {
  ProtectedDiscoverCategorySlugRoute: ProtectedDiscoverCategorySlugRoute,
  ProtectedDiscoverIndexRoute: ProtectedDiscoverIndexRoute,
}

const ProtectedDiscoverRouteWithChildren =
  ProtectedDiscoverRoute._addFileChildren(ProtectedDiscoverRouteChildren)

interface ProtectedDashboardAiRouteChildren {
  ProtectedDashboardAiThreadIdRoute: typeof ProtectedDashboardAiThreadIdRoute
  ProtectedDashboardAiIndexRoute: typeof ProtectedDashboardAiIndexRoute
}

const ProtectedDashboardAiRouteChildren: ProtectedDashboardAiRouteChildren = {
  ProtectedDashboardAiThreadIdRoute: ProtectedDashboardAiThreadIdRoute,
  ProtectedDashboardAiIndexRoute: ProtectedDashboardAiIndexRoute,
}

const ProtectedDashboardAiRouteWithChildren =
  ProtectedDashboardAiRoute._addFileChildren(ProtectedDashboardAiRouteChildren)

interface ProtectedRouteChildren {
  ProtectedFolderSlugRoute: typeof ProtectedFolderSlugRouteWithChildren
  ProtectedAllRoute: typeof ProtectedAllRoute
  ProtectedDiscoverRoute: typeof ProtectedDiscoverRouteWithChildren
  ProtectedFavoritesRoute: typeof ProtectedFavoritesRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedSourcesRoute: typeof ProtectedSourcesRoute
  ProtectedTodayRoute: typeof ProtectedTodayRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedDashboardAiRoute: typeof ProtectedDashboardAiRouteWithChildren
  ProtectedDeveloperKeysRoute: typeof ProtectedDeveloperKeysRoute
  ProtectedDeveloperMcpRoute: typeof ProtectedDeveloperMcpRoute
  ProtectedFeedFeedSlugRoute: typeof ProtectedFeedFeedSlugRoute
  ProtectedSettingsWorkspacesSlugRoute: typeof ProtectedSettingsWorkspacesSlugRoute
  ProtectedWorkspacesSlugSettingsRoute: typeof ProtectedWorkspacesSlugSettingsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedFolderSlugRoute: ProtectedFolderSlugRouteWithChildren,
  ProtectedAllRoute: ProtectedAllRoute,
  ProtectedDiscoverRoute: ProtectedDiscoverRouteWithChildren,
  ProtectedFavoritesRoute: ProtectedFavoritesRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedSourcesRoute: ProtectedSourcesRoute,
  ProtectedTodayRoute: ProtectedTodayRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedDashboardAiRoute: ProtectedDashboardAiRouteWithChildren,
  ProtectedDeveloperKeysRoute: ProtectedDeveloperKeysRoute,
  ProtectedDeveloperMcpRoute: ProtectedDeveloperMcpRoute,
  ProtectedFeedFeedSlugRoute: ProtectedFeedFeedSlugRoute,
  ProtectedSettingsWorkspacesSlugRoute: ProtectedSettingsWorkspacesSlugRoute,
  ProtectedWorkspacesSlugSettingsRoute: ProtectedWorkspacesSlugSettingsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  FolderSlugFeedRoute: FolderSlugFeedRoute,
  FolderSlugXmlRoute: FolderSlugXmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiWorkspaceDataRoute: ApiWorkspaceDataRoute,
  SprkFolderSlugRoute: SprkFolderSlugRoute,
  FolderSlugFeedSlugFeedRoute: FolderSlugFeedSlugFeedRoute,
  FolderSlugFeedSlugXmlRoute: FolderSlugFeedSlugXmlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDodoWebhooksRoute: ApiDodoWebhooksRoute,
  ApiFeedsShareRoute: ApiFeedsShareRoute,
  ApiFoldersAddToWorkspaceRoute: ApiFoldersAddToWorkspaceRoute,
  ApiFoldersShareRoute: ApiFoldersShareRoute,
  ApiRssSlugRoute: ApiRssSlugRoute,
  ApiSharedFolderIdRoute: ApiSharedFolderIdRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiInternalPlatformSplatRoute: ApiInternalPlatformSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
